movie_project/movie_app/urls.py
from django.urls import path
from . import views
app_name = "movie_app"
urlpatterns = [
    path('', views.index, name="index"),
    path('movie/<int:movie_id>/', views.details, name="details"),
    path('add/', views.add_movie, name="add_movie"),
    path('update/<int:movie_id>/', views.update_movie, name="update_movie"),
    path('delete/<int:movie_id>', views.delete_movie, name="delete_movie"),

]

movie_project/movie_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("movie_app.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_project/movie_app/models.py
from django.db import models

# Create your models here.


class Movie(models.Model):
    title = models.CharField(max_length=50)
    desc = models.TextField(max_length=500)
    release_year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.title

movie_project/movie_app/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['title', 'desc', 'release_year', 'img']

movie_project/movie_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm

# Create your views here.


def index(request):
    movie = Movie.objects.all()
    return render(request, "index.html", {'movie': movie})


def details(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "details.html", {'movie': movie})


def add_movie(request):
    if request.method == "POST":
        title = request.POST.get('title',)
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie = Movie(title=title, desc=desc, release_year=year, img=img)
        movie.save()
        return redirect('/')
    return render(request, 'add_movie.html')


def update_movie(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, "edit.html", {'form': form, 'movie': movie})


def delete_movie(request, movie_id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=movie_id)
        movie.delete()
        return redirect('/')
    return render(request, "delete.html")

movie_project/templates/add_movie.html
{% extends 'base.html' %}
{% block body %}
<div align="center">
    <form method="POST" enctype="multipart/form-data"> {% csrf_token %}
        <input type="text" name="title" placeholder="Movie Title"> <br> <br>
        <input type="text" name="desc" placeholder="Movie Description"> <br> <br>
        <input type="number" name="year" placeholder="Release Year"> <br> <br>
        <input type="file" name="img"> <br> <br>
        <input type="submit">
    </form>
</div>
    {% endblock %}

movie_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">MOVIES</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <span class="navbar-text">
            <a href="{% url 'movie_app:add_movie' %}">
                <button type="button" class="btn btn-light">Add Movie</button>
            </a>
      </span>
    </div>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movie_project/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data"> {% csrf_token %}
    <div align="center">
    <h3>Delete movie??</h3>
    <button type="submit" class="btn btn-outline-danger">Delete</button>
    </div>
</form>
{% endblock %}

movie_project/templates/details.html
{% extends 'base.html' %}
{% block body %}
<br><br>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>
        <div class="col-md-8">
            <h1 align="center">{{movie.title}}</h1><br>
            <b>Description:</b>{{movie.desc}}<br><br>
            <b>Release Year:</b>{{movie.release_year}}<br><br>
            <a href="{% url 'movie_app:update_movie' movie.id %}">
                <button type="button" class="btn btn-outline-primary">Update</button>
            </a>
            <a href="{% url 'movie_app:delete_movie' movie.id %}">
                <button type="button" class="btn btn-outline-danger">Delete</button>
            </a>
        </div>
    </div>
</div>

{% endblock %}

movie_project/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data"> {% csrf_token %}
    {{ form.as_p}}
    <input type="submit">
</form>
{% endblock %}

movie_project/templates/index.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <div class="row">
            {% for i in movie %}
            <div class="col-md-3">
                <div class="card" style="width: 18rem;">
                    <img src="{{i.img.url}}" class="card-img-top" alt="..." height="250">
                    <div class="card-body">
                        <h5 class="card-title">{{i.title}}</h5>
<!--                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>-->
                        <a href="{% url 'movie_app:details' i.id %}" class="btn btn-primary">Click for details</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}